# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160907_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelisting',
            name='applicant_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
