# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160912_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelisting',
            name='applicant_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/app/images/'),
        ),
    ]
