# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160912_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelisting',
            name='applicant_image',
            field=models.ImageField(default='static/app/images/None/no-img.jpg', upload_to='static/app/images/'),
        ),
    ]
