# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160912_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelisting',
            name='applicant_image',
            field=models.ImageField(default='uploads/None/no-img.jpg', upload_to='uploads'),
        ),
    ]
