# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160912_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelisting',
            name='applicant_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
